name: CI/CD workflow for Maven Build and Sonar Code scan
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  sonarQube:
    name: SonarQube Scan
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'

    - name: Cache SonarQube packages
      uses: actions/cache@v3
      with:
        path: C:\Users\runneradmin\.sonar\cache
        key: ${{ runner.os }}-sonar

    - name: Download SonarQube Scanner
      run: |
        curl -sSLo sonar-scanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.6.2.2472-windows.zip
        Expand-Archive -Path sonar-scanner.zip -DestinationPath C:\Users\runneradmin\sonar-scanner
        Rename-Item -Path (Get-ChildItem -Path C:\Users\runneradmin\sonar-scanner -Directory) -NewName "sonar-scanner"

    - name: SonarQube Scan
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        SONAR_SCANNER_HOME: C:\Users\runneradmin\sonar-scanner\sonar-scanner
      run: |
        $env:Path += ";$env:SONAR_SCANNER_HOME\bin"
        sonar-scanner.bat `
          -Dsonar.projectKey=your_project_key `
          -Dsonar.sources=. `
          -Dsonar.host.url=$env:SONAR_HOST_URL `
          -Dsonar.login=$env:SONAR_TOKEN
